df<- read.table("F://JHU/household_power_consumption.txt", header = TRUE)
library(dplyr)
library(tidyr)
df<- df%>%
  separate(Date.Time.Global_active_power.Global_reactive_power.Voltage.Global_intensity.Sub_metering_1.Sub_metering_2.Sub_metering_3, c("Date", "Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity", 'Sub_metering_1', "Sub_metering_2","Sub_metering_3"), ";")
df$Global_active_power<- as.numeric(df$Global_active_power)
df$Date<- as.Date(df$Date, "%d/%m/%Y")
df$weekday<- weekdays(df$Date)
df$CHR<- as.POSIXct(paste(df$Date, df$Time), format= "%Y-%m-%d %H:%M:%S", usetz=FALSE)
png("plot4.png")
par(mfrow= c(2,2))
plot(df$CHR, df$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
plot(df$CHR, df$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(df$CHR,df$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(df$CHR, df$Sub_metering_2, type = "l", col="red")
lines(df$CHR, df$Sub_metering_3, type = "l", col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3") , col = c("black", "red","blue"), pch="___")
plot(df$CHR, df$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_Reactive_Power")
dev.off()
